version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: vizsgaremek_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: vizsgaremek
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
